Improve shallow merge

diff --git a/bash-functions b/bash-functions
--- a/bash-functions
+++ b/bash-functions
@@ -236,45 +236,46 @@ resolveVersionConflict() {
   fi
 }
 
-updateBranch() {
-  local other=$1
-  local current=$(git branch --show-current)
-  echo "Merging branch ${other} into ${current}"
-  git pull --progress --ff $REMOTE $other || resolveVersionConflict
-}
+# updateBranch() {
+#   local other=$1
+#   local current=$(git branch --show-current)
+#   echo "Merging branch ${other} into ${current}"
+#   git pull --progress --ff $REMOTE $other || resolveVersionConflict
+# }
 
 shallowFetch() {
   local branch=$1
   local exclude=$2
+  echo "Fetching commits from ${exclude} to ${branch}"
   git fetch --progress --shallow-exclude=$exclude $REMOTE $branch && git gc
+}
+
+shallowFail() {
+  local error=$1
+  echo "Fetch failed with code ${error}"
 }
 
 shallowMerge() {
   local branch=$1
-  local into=$2
-
-  if [ -z "$into" ]; then
-    into=$(git branch --show-current)
-  fi
+  local into=$(git branch --show-current)
 
   echo "Merging branch ${branch} into ${into}"
 
   ## Fetch minimal history from both branches
-  shallowFetch $branch $into || true
-  shallowFetch $into $branch || true
+  shallowFetch $branch $into || shallowFail $?
+  shallowFetch $into $branch || shallowFail $?
+  echo "Fetching additional commit for ${branch} and ${into}"
   git fetch --progress --deepen=1 $REMOTE $branch $into
 
-  git checkout $into
   git merge $REMOTE/$branch || resolveVersionConflict
 }
 
 updateDev() {
   local branch=$1
-  local into=$2
 
   setGitIdentity
   # updateBranch $branch
-  shallowMerge $branch $into
+  shallowMerge $branch
 
   updateVersion $V_MINOR
 
